### ISSUE TITLE
Could not find com.yandex.money:checkout:1.3.0.3.

### ISSUE THREAD

**Issue by priyanka114** [yandex-money/yandex-checkout-android-sdk#10]
When I tried adding dependency implementation 'com.yandex.money:checkout:1.3.0.3', I got following error. What could be the reason?

![screen shot 2018-09-21 at 5 50 35 pm](https://user-images.githubusercontent.com/20013870/45880924-29123200-bdc7-11e8-991d-911c1b9dfd4b.png)

**Comment by lynnfield** [comment]
Hi. You forget to add our bintray repository to your repositories section in build.gradle file. Check Readme.md for more information.

**Comment by priyanka114** [comment]
Thank you for replying.. 
I have added bintray repository in project level build.gradle like following screenshot :>

![screen shot 2018-09-24 at 11 08 46 am](https://user-images.githubusercontent.com/20013870/45939156-0e6dd200-bfee-11e8-96a2-838f88070dc6.png)

Even I tried running the sample code provided in your repo but issue is same with minor changes in error. Following is the screenshot after compilation of the yandex-checkout-android-sdk-master :>

![screen shot 2018-09-24 at 11 44 04 am](https://user-images.githubusercontent.com/20013870/45939348-707b0700-bfef-11e8-8593-1168482c0e8c.png)

**Comment by lynnfield** [comment]
You should add bintray repository to `allprojects.repositories` instead of buildscript.repositories

**Comment by abrusdev** [comment]
it doesn't help me
