### ISSUE TITLE
Проблема после авторизации

### ISSUE THREAD

**Issue by gish94** [yandex-money/yandex-checkout-android-sdk#11]
Загрузка крутится бесконечно после авторизации

**Comment by drukarev** [comment]
Можете предоставить какие-нибудь дополнительные данные?
1) Какие методы Checkout вызывались и с какими параметрами.
2) Подключена ли Yandex authsdk
3) Переопределен ли YANDEX_CLIENT_ID в build.gradle

**Comment by gish94** [comment]
> Можете предоставить дополнительные данные?
> 
> 1. Какие методы Checkout вызывались и с какими параметрами.
> 2. Подключена ли Yandex authsdk
> 3. Переопределен ли YANDEX_CLIENT_ID в build.gradle

1.   HashSet<PaymentMethodType> paymentMethods = new HashSet<>();
      paymentMethods.add(PaymentMethodType.YANDEX_MONEY);
      paymentMethods.add(PaymentMethodType.BANK_CARD);
2.    implementation 'com.yandex.android:authsdk:2.1.0'

3. определен без него на сайте выдает ошибку

**Comment by drukarev** [comment]
Ещё несколько вопросов:
1) В коде вызывается Checkout.configureTestMode()? Если вызывается, то с какими параметрами?
2) Я правильно понимаю, что сперва открывается список платежных инструментов, затем вы жмете на кошелек, авторизуетесь, и после этого возвращаетесь в приложение с крутящимся спиннером? Или имеется в виду платежная авторизация с кодом подтверждения?
3) Какая версия msdk используется?

**Comment by gish94** [comment]
> Ещё несколько вопросов:
> 
> 1. В коде вызывается Checkout.configureTestMode()? Если вызывается, то с какими параметрами?
> 2. Я правильно понимаю, что сперва открывается список платежных инструментов, затем вы жмете на кошелек, авторизуетесь, и после этого возвращаетесь в приложение с крутящимся спиннером? Или имеется в виду платежная авторизация с кодом подтверждения?
> 3. Какая версия msdk используется?

1. нет, используются данные для релиза.
2. нет, когда вызиваю Checkout.tokenize() без configureTestMode() сразу перенаправляэт на авторизацию и при возврашении в приложение спинер крутится безконечно 
3. com.yandex.money:checkout:1.3.0.3

**Comment by gish94** [comment]
Нужна какая нибудь ещё информация?

**Comment by drukarev** [comment]
1) Авторизация проходит успешно, прежде чем вы возвращаетесь на предыдущий экран?
2) У пользователя, которым вы авторизуетесь, есть кошелек яндекс.денег? Если нет, попробуйте пользователя с привязанным кошельком.

**Comment by gish94** [comment]
> 1. Авторизация проходит успешно, прежде чем вы возвращаетесь на предыдущий экран?
> 2. У пользователя, которым вы авторизуетесь, есть кошелек яндекс.денег? Если нет, попробуйте пользователя с привязанным кошельком.

1. да
2. есть
