### ISSUE TITLE
Как понять что платеж требует авторизации по 3DSecure?

### ISSUE THREAD

**Issue by VaDRo** [yandex-money/yandex-checkout-android-sdk#12]
Насколько я понял из описания API, activity подтверждения платежа через 3D Secure должна отображаться по выбору конечного разработчика. Подскажите пожалуйста - исходя из каких критериев я должен принимать решение о необходимости отображения данной activity?

**Comment by lynnfield** [comment]
Здравствуйте. Требование провести подтверждение платежа на основе 3DS появляется в момент проведения платежа. То есть после того, как Вы получили платежный токен от Checkout, Вы должны отправить его на свой сервер для проведения оплаты. В процессе проведения оплаты вы получите ответ о необходимости пройти 3DS, который надо вернуть на Ваш мобильный клиент и вызвать соответствующий экран. После успешного прохождения 3DS необходимо повторить проведение платежа с тем же токеном.

**Comment by IldarFattakhov** [comment]
>  После успешного прохождения 3DS необходимо повторить проведение платежа с тем же токеном.

Здравствуйте. А это точно, что нужно слать еще раз запрос? Или все таки надо ждать уведомления или обновлять статус?
