### ISSUE TITLE
Проблема с 3ds

### ISSUE THREAD

**Issue by givotnoe** [yandex-money/yandex-checkout-android-sdk#14]
День добрый. 

При выполнении оплаты с использованием Checkout.create3dsIntent(), onActivityResult() выходит в сценарий "case Checkout.RESULT_ERROR:" с data.getStringExtra(Checkout.EXTRA_ERROR_DESCRIPTION) - "Не удалось установить безопасное соединение", data.getStringExtra(Checkout.EXTRA_ERROR_FAILING_URL) - "https://paymentcard.yamoney.ru/gates/sberbank3ds" (в моем случае). 

Проблема с хендшейком воспроизводится на Samsung Galaxy S4 Mini API 17, начиная с API 19 исчезает, на собственной вебвью (без использования create3dsIntent) также присутствует на API < 19. TLS 1.2 включен через security provider.

**Comment by drukarev** [comment]
Fixed in 1.3.0.5
