### ISSUE TITLE
Ошибка при интеграции библиотеки

### ISSUE THREAD

**Issue by Tiotenshi** [yandex-money/yandex-checkout-android-sdk#15]
Добрый день!
Пытаюсь прикрутить библиотеку к проекту Xamarin.Android на Visual Studio и при билде получаю ошибку:
'Size' does not implement interface member 'IComparable.CompareTo(Object)'		\obj\Debug\generated\src\Cards.Pay.Paycardsrecognizer.Sdk.Utils.Size.cs

Последовательность действий:
В солюшне создаю Android Binding Library (Xamarin), в папку jars кладу файл pay-cards-sdk.aar и ставлю Build Action для него, как LibraryProjectZip. Жму Build и получаю ошибку.

**Comment by lynnfield** [comment]
Здравствуйте.
Кажется, это проблема интеграции Xamarin и PayCards sdk.
Мы не можем с этим помочь, но, думаю, что на StackOverflow или подобных сайтах есть ответы.
