### ISSUE TITLE
Rxjava

### ISSUE THREAD

**Issue by rudemiguel** [yandex-money/yandex-checkout-android-sdk#19]
Хочу использовать RxJava для процесса токенизации
Пробую обернуть вызовы Checkout.setResultCallback Checkout.tokenize в Observabable, проблема в том при какой либо ошибке Checkout.ResultCallback не вызывается а вызывается только после успешной токенизации.
Если ли способ получить событие о том что токенизация завершилась с ошибкой?

**Comment by drukarev** [comment]
В текущем флоу все ошибки отображаются на стороне мсдк. 
Из мсдк может вернуться только успешно полученный токен (либо пользователь нажмёт назад и отменит токенизацию).
