### ISSUE TITLE
Некоторые приложения собранные с версией SDK 2.0 нельзя использовать из-за требований Google Play 

### ISSUE THREAD

**Issue by chim0380** [yandex-money/yandex-checkout-android-sdk#20]
В вашей библиотеке есть возможность оплаты через Google Pay. Согласно правилам Google Pay его можно использовать только для приобретения не цифровых товаров. Приложения с оплатой услуг или например с приобритением премиум доступа внутри приложения не могут принимать платежи через Google Pay.
При публикации в  маркет Google Play таких приложений, собранных с Вашей библиотекой, происходит отказ в публикации( с указанием причины отказа). Ранее, для версий Вашей библиотеки до версий 2.0, я решал эту проблему путем указания в файле манифеста  удаления **com.google.android.gms.wallet.api.enabled**
 

```
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            tools:node="remove" />
```

Хочу заметить что необходимо именно **удаление параметра** , замена значения на false все равно приводило к отказу в публикации.

Теперь,  версии SDK 2.0 ,наличие этого переопределения в манифесте  всегда вызывает падение приложения сразу после вызова Checkout.createTokenizeIntent. Причем падение происходит и в том случае, если запретить Google Pay на уровне  paymentMethodTypes, то есть указать только:

```
final Set<PaymentMethodType> paymentMethodTypes = new HashSet<>();
                paymentMethodTypes.add(PaymentMethodType.BANK_CARD);
                paymentMethodTypes.add(PaymentMethodType.SBERBANK);
                paymentMethodTypes.add(PaymentMethodType.YANDEX_MONEY);
```
Если убрать из манифеста переопределение, то SDK работает.

Прошу, сделать SDK рабочим при наличии переопределения в манифесте:

```
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            tools:node="remove" />
```

**Comment by drukarev** [comment]
Добрый день.
Хочу уточнить несколько деталей. Если возможно, пришлите ответ на yamoney_shop@yamoney.ru
1) На какой именно стадии происходит отказ в публикации? (и скриншот причины отказа)
2) Я правильно понял, что отказ на прошлых версиях был даже в случае, если в приложении нельзя было выбрать Google Pay как платежный инструмент?

**Comment by drukarev** [comment]
Fixed in 2.1.0
