### ISSUE TITLE
Нет логов при TestParameters.showLogs (true)

### ISSUE THREAD

**Issue by ITurchenko** [yandex-money/yandex-checkout-android-sdk#23]
Версия библиотеки `com.yandex.android:authsdk:2.1.0`
дебаговая сборка без прогуарда, подписанная

```
val p = PaymentParameters( ... )
val testParameters = TestParameters(true)
val intent = Checkout.createTokenizeIntent(context ?: return, p, testParameters)
```

При запуске нет логов. Соответственно никакой возможности самостоятельно локализовать причину ошибки "Что-то пошло не так, мы чиним, можете попробовать ещё раз" при попытке оплаты.

**Comment by ITurchenko** [comment]
Проблема воспроизводится не на всех устройствах.

Наблюдается на Honor 5C, Android 7.0, EMUI 5.0.4, на телефоне установлено приложение Яндекс.Денег

Отсутствует на Nexus 5, Android 6.0.1, приложения Яндекс.Денег нет

**Comment by drukarev** [comment]
Добрый день. Пока не смогли воспроизвести проблему. Есть возможность дать минимальный проект, на котором воспроизводится проблема с логами и ошибка?

**Comment by ITurchenko** [comment]
Добрый день.
Да, конечно. Предоставляю мини-проект в котором воспроизводится проблема - отсутствие логов

[YKassaDemo.zip](https://github.com/yandex-money/yandex-checkout-android-sdk/files/2991496/YKassaDemo.zip)

Ожидание - логи в консоли с тегом "Yandex.Checkout.SDK" о неправильных ключах авторизации
Поведение на Honor 5C, Android 7.0, EMUI 5.0.4 - отсутствие логов с тегом "Yandex.Checkout.SDK"

Есть подозрение, что проблема как-то связана с оболочкой EMUI, т.к. при проверке на доступных телефонах с "чистым" андроидом проблему не удалось воспроизвести.

**Comment by ITurchenko** [comment]
Коллеги, кажется нашел причину. Старый баг(?) андроида о том, что не все телефоны выводят логи [уровня "debug" и "verbose"](https://stackoverflow.com/questions/28434901/why-are-log-d-and-log-v-not-printing). 

При повышении уровня хотя бы до "info" логи выводятся всегда и на всех устройствах.

В связи с этим у меня вопрос/предложение - можно ли добавить возможность подключения "своего" логгера, чтобы я мог при необходимости менять уровень логирования и выводить сообщения на экран для облегчения отладки?

**Comment by drukarev** [comment]
Добрый день.
Судя по комментариям (https://stackoverflow.com/questions/28434901/why-are-log-d-and-log-v-not-printing), проблему можно решить с помощью настроек разработчика.
Возможность подключения своего логгера и изменения уровня логирования пока не планируется, так-как мы не хотим, чтобы логи случайно оказались в релизных сборках приложений.
