### ISSUE TITLE
Падение при обработке результата токенизации

### ISSUE THREAD

**Issue by ARRR42** [yandex-money/yandex-checkout-android-sdk#24]
Если вызвать 'Checkout.createTokenizationResult(data)' c data == null, или если в data не будет соответствующего Serializable объекта PaymentMethodType, произойдет краш.

```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
TokenizationResult tokenizationResult = Checkout.createTokenizationResult(data);
...
}
```

Краш: 

 ```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=84, result=84, data=Intent { flg=0x3 (has extras) }} to activity {***.ui.activities.MainActivity}: kotlin.TypeCastException: null cannot be cast to non-null type ru.yandex.money.android.sdk.PaymentMethodType
```

В Checkout.createTokenizationResult() используется небезопасное приведение типов:

`val type = data.getSerializableExtra(EXTRA_PAYMENT_METHOD_TYPE) as PaymentMethodType`

**Comment by drukarev** [comment]
Данные с Activity возвращаются данные в сериализованном виде, поэтому там не может быть безопасного приведения типов.
Checkout.createTokenizationResult(data) стоит применять, когда мы уверены, что вернулись с нужного экрана и получили RESULT_OK. Можно сделать, как в примере: https://github.com/yandex-money/yandex-checkout-android-sdk#получение-результата-токенизации

С нашей стороны добавим более подробную информацию об этом методе в Javadoc и README, и сделаем понятный exception в случае, если метод вызывается из java-кода, и в поле data передаётся null.
