### ISSUE TITLE
Значения PaymentMethodType

### ISSUE THREAD

**Issue by Slaggery** [yandex-money/yandex-checkout-android-sdk#30]
Добрый день! не нашел нигде информации как выбрать несколько значений в поле Set of PaymentMethodType.
В документации сказано что если поле оставить пустым, то выбираются все значения. А есть ли возможность выбора двух способов оплаты, а не всех четырех?

**Comment by drukarev** [comment]
Добрый день. Да, можно выбрать любое количество методов оплаты.
Тип поля paymentMethodTypes - Set, в него можно положить несколько неповторяющихся значений.
Возможные значения перечислены здесь - https://github.com/yandex-money/yandex-checkout-android-sdk#запуск-токенизации - в разделе "Значения PaymentMethodType"
Достаточно создать любой Set, положить в него нужные способы оплаты и передать как параметр paymentMethodTypes
