### ISSUE TITLE
Возвращение неверного статуса

### ISSUE THREAD

**Issue by labrador116** [yandex-money/yandex-checkout-android-sdk#31]
При использовании тестовый карты с поведением 3d_secure_failed активити для проверки смс-кода (Checkout.create3dsIntent()) возвращает -1 (Activity.RESULT_OK), хотя должна вернуть Checkout.RESULT_ERROR

**Comment by drukarev** [comment]
Добрый день.
Результат "Activity.RESULT_OK" означает, что процесс 3-DS успешно завершился (то есть, он не был отменён и прошёл без технических ошибок). Этот ответ не гарантирует, что при проведении 3-DS был введён правильный код.

**Comment by labrador116** [comment]
Спасибо, понял вас. Просто в документации не было конкретизировано и ожидал, что функционал ваидации результата встроен в библиотеку.

**Comment by drukarev** [comment]
Согласен, там не очень понятно; мы поправим документацию.
