### ISSUE TITLE
onBackPressed() not close Activity created by Checkout.createTokenizeIntent

### ISSUE THREAD

**Issue by DmitrSP** [yandex-money/yandex-checkout-android-sdk#33]
Если вызвать Checkout.createTokenizeIntent(), а после появления Фрагмента Яндекс с кнопкой Продолжить нажать onBack, Фрагмент убегает - ок. Жму еще раз onBack - замечаю, что-то исчезает с экрана (похоже на активити с прозрачным фоном). Жму еще onBack и только теперь мое активити начинает реагировать.. При этом, если ЯндексФрагмент с кнопкой Продолжить свайпнуть вниз, чтобы он исчез, то такого странного поведения не наблюдаю. Мое  активити реагирует на onBackPressed() сразу, с первого раза. Поправьте, плиз

**Comment by whalemare** [comment]
Плюсую, зашел сюда чтобы создать такой же issue. Прилагаю gif с тем, как это выглядит (5мб)
![android_bug](https://user-images.githubusercontent.com/9128731/64397965-5a921500-d08d-11e9-8800-a90e082575b6.gif)

**Comment by drukarev** [comment]
Добрый день. Несколько вопросов для уточнения проблемы:
1) На каких устройствах воспроизводится проблема?
2) В демо библиотеки (https://play.google.com/store/apps/details?id=ru.yandex.money.android.example.prod) на ваших устройствах проблема также воспроизводится?
3) Какая версия библиотеки используется?

Если есть какой-то минимальный проект, где воспроизводится проблема, пришлите его, пожалуйта.

**Comment by DmitrSP** [comment]
> Добрый день. Несколько вопросов для уточнения проблемы:
> 
> 1. На каких устройствах воспроизводится проблема?
> 2. В демо библиотеки (https://play.google.com/store/apps/details?id=ru.yandex.money.android.example.prod) на ваших устройствах проблема также воспроизводится?
> 3. Какая версия библиотеки используется?
> 
> Если есть какой-то минимальный проект, где воспроизводится проблема, пришлите его, пожалуйста.

Установил демо библиотеки. Кажется, понял в чем проблема... В моем приложении можно оплачивать только картой. Т. е. выбор способа оплаты у меня отсутствует. И что происходит в демо - кликаю Купить, вижу Способ оплаты, выбираю банковскую карту, вижу новый фрагмент. Жму назад - вижу Способ оплаты. А если не жму, а свайпаю (после выбора способа), то Способ оплаты не появляется. Согласен, что в данном случае появление фрагмента со Способами оплаты логично, но предусмотрите, что может быть только один способ оплаты и экран с выбором способа не появляется...

1. Эмулятор (API >=27), Xiaomi Redmi 3... Думаю причина не в устройстве...
3. 'com.yandex.money:checkout:2.3.0'

**Comment by whalemare** [comment]
@drukarev посмотрите вот этот проект, на нем можно поиграться
https://github.com/lamantin-group/react-native-yandex-payment/tree/develop

единственное, это `react-native` и чтобы запустить нужно выполнить:
```bash
git clone https://github.com/lamantin-group/react-native-yandex-payment
cd react-native-yandex-payment
git checkout develop
npm run doctor
# здесь нужно запустить эмулятор, либо подключить реальный андроид девайс
npm run android
```

**Comment by drukarev** [comment]
Не смогли воспроизвести проблему на наших устройствах, но возможно нашли её причину.
Попробуйте проверить в версии 2.4.1, воспроизводится ли баг.

**Comment by drukarev** [comment]
Closed with https://github.com/yandex-money/yandex-checkout-android-sdk/issues/36
