### ISSUE TITLE
Не отображается логотип Яндекс.Кассы

### ISSUE THREAD

**Issue by KirillArtemenko** [yandex-money/yandex-checkout-android-sdk#35]
Не могу отобразить логотип Яндекс.Кассы, пробовал и дефолтные значения и явно задавать UiParameters, ничего.

```
// пример 1
Intent intent = Checkout.createTokenizeIntent(appContext, paymentParameters);

// пример 2
UiParameters uiParameters = new UiParameters(true);
Intent intent = Checkout.createTokenizeIntent(appContext, paymentParameters, new TestParameters(), uiParameters);

// пример 3, с изменением цвета кнопки
UiParameters uiParameters = new UiParameters(true, new ColorScheme(Color.rgb(70, 190, 100)));
Intent intent = Checkout.createTokenizeIntent(appContext, paymentParameters, new TestParameters(), uiParameters);
```

![nologo](https://user-images.githubusercontent.com/667503/64952726-b7f64500-d889-11e9-853a-16ce340e0950.jpg)

Окно оплаты открывается, цвет кнопки изменяется (пример 3), но логотипа в углу нет.

**Comment by KirillArtemenko** [comment]
Заметил, что во время загрузки он есть, но на основном экране исчезает.

**Comment by drukarev** [comment]
Логотип кассы отображается только на экране выбора способа оплаты. На контракте его нет.
В данном случае доступен только один способ оплаты, поэтому экран с логотипом пропускается.

**Comment by KirillArtemenko** [comment]
Да вы правы, мое упущение, закрываю эту проблему.
