### ISSUE TITLE
Проблемы с действием назад на OnePlus

### ISSUE THREAD

**Issue by KirillArtemenko** [yandex-money/yandex-checkout-android-sdk#36]
Если сразу после открытия кассы нажать кнопку назад, касса скрывается но при при тапе в любое место ничего не происходит. После этого нужно еще раз нажать системную кнопку назад и только тогда видна анимация словно еще один невидимый слой закрылся и тога отрабатывает onActivityResult и интерфейс снова работает как надо. Возможно проблема проявляется только на OnePlus. Версия пакета 2.4.0

**Comment by KirillArtemenko** [comment]
Проблема до сих пор сохраняется и требует решения.

**Comment by drukarev** [comment]
Не смогли воспроизвести проблему на наших устройствах, но возможно нашли её причину.
Попробуйте проверить в версии 2.4.1, воспроизводится ли баг.

**Comment by KirillArtemenko** [comment]
Баг более не воспроизводится, проблема решена!
