### ISSUE TITLE
Не работает Google Pay

### ISSUE THREAD

**Issue by radugaTheIOSDeveloper** [yandex-money/yandex-checkout-android-sdk#38]
Добрый день! Имеем вресию приложения, которая уже выложена в маркет. На текущий момент разрабатываем новую. applicatioID, package_name ... все соответсвует.
При попытке сделать платеж через google pay получаем слудующу ошибку : Не удалось выполнить запрос, этот продавец не зарегестрирован в сервисе google pay.
Оплата по банковской карте проходит.
`        final Set<PaymentMethodType> paymentMethodTypes = new HashSet<>();
        paymentMethodTypes.add(PaymentMethodType.GOOGLE_PAY);
        paymentMethodTypes.add(PaymentMethodType.BANK_CARD);

        final Set<GooglePayCardNetwork> allowedCardNetworks = new HashSet<>();
        allowedCardNetworks.add(GooglePayCardNetwork.MASTERCARD);
        allowedCardNetworks.add(GooglePayCardNetwork.VISA);
        //allowedCardNetworks.add(GooglePayCardNetwork.OTHER);

        PaymentParameters paymentParameters = new PaymentParameters(
                new Amount(amount, Currency.getInstance("RUB")),
                "Название товара",
                "Описание товара",
                "live_********",
                "629818",
                paymentMethodTypes,
                null,
                null,
                null,
                new GooglePayParameters(allowedCardNetworks)
        );`

**Comment by drukarev** [comment]
Добрый день. Ошибка возникает из-за того, что у вас не пройдена интеграция с Google Pay.
Напишите yamoney_shop@yamoney.ru, вас сориентируют, что нужно сделать.

**Comment by MaxEpt** [comment]
> Добрый день. Ошибка возникает из-за того, что у вас не пройдена интеграция с Google Pay.
> Напишите [yamoney_shop@yamoney.ru](mailto:yamoney_shop@yamoney.ru), вас сориентируют, что нужно сделать.

Именно это и сделали. Отсылают в техподдержку гугл. Но с чем мы к ним обратимся, если взаимодействие с GOOGLE PAY API лежит на стороне SDK? Возможно с вашей стороны нужна какая то регситрация нашего application ID ?

**Comment by Varius1** [comment]
> > Добрый день. Ошибка возникает из-за того, что у вас не пройдена интеграция с Google Pay.
> > Напишите [yamoney_shop@yamoney.ru](mailto:yamoney_shop@yamoney.ru), вас сориентируют, что нужно сделать.
> 
> Именно это и сделали. Отсылают в техподдержку гугл. Но с чем мы к ним обратимся, если взаимодействие с GOOGLE PAY API лежит на стороне SDK? Возможно с вашей стороны нужна какая то регситрация нашего application ID ?

Удалось как то решить проблему?

**Comment by MaxEpt** [comment]
Проблема оказалось в том, что да, действительно нужно пройти интеграцию с Google PAY. Но в документации яндекса на момент интеграция сервиса нами ничего об этом не сказано. Все что отвечала тех.поддержка - Обратитесь в гугл, у нас все ок.
Для того, чтобы Google PAY заработал:

1.  Включить в sdk тестовый режим, Google PAY начнет открываться, но платежи проходить не будут.
2.  Сделать "Заглушку" в приложении, для тестового режима, т.е при учете того, что платеж тестовый показать экран успешно совершенной покупки.
3.  Заснять все на видео, на другое устройство(видео с экрана писать не выйдет) 
4. Выложить заснятое видео куда-нибудь, мы использовали google drive(ну гугл же :) )
5. Идем заполнять форму https://services.google.com/fb/forms/googlepayAPIenable/
**Tokenization Method ** Оставляем Gateway
**Payment Processor or Gateway** мы вписали там YandexCheckout
**Please provide a shared Drive link to any applicable attachments ** Здесь ссылку на видео
**Merchant Name ** Здесь поставили схожее с названием приложения )) 
Надеюсь, ребята из яндекса расскажут подробнее что где и как заполнять) А может и уже рассказали, честно - не посмотрел
