### ISSUE TITLE
result code при 3d secure

### ISSUE THREAD

**Issue by MaxEpt** [yandex-money/yandex-checkout-android-sdk#46]
Добрый день! При обработке 3d secure, в случае, например, если у пользователя нет денег на карте, мы полчаем result_code = -1, при этом в случае успеха мы получаем также -1
`        if (requestCode == 1) {
            switch (resultCode) {
                case RESULT_OK:
                    // 3ds прошел
                    break;
                case RESULT_CANCELED:
                    // экран 3ds был закрыт
                    break;
                case Checkout.RESULT_ERROR:
                    // во время 3ds произошла какая-то ошибка (нет соединения или что-то еще)
                    // более подробную информацию можно посмотреть в data
                    // data.getIntExtra(Checkout.EXTRA_ERROR_CODE) - код ошибки из WebViewClient.ERROR_* или Checkout.ERROR_NOT_HTTPS_URL
                    // data.getStringExtra(Checkout.EXTRA_ERROR_DESCRIPTION) - описание ошибки (может отсутствовать)
                    // data.getStringExtra(Checkout.EXTRA_ERROR_FAILING_URL) - url по которому произошла ошибка (может отсутствовать)
                    break;
            }`

**Comment by drukarev** [comment]
Добрый день.
RESULT_OK говорит о том, что операция 3-DS была совершена. Статус платежа после этого нужно узнать с помощью повторного вызова /payments. Подробнее про жизненный цикл платежа можно посмотреть здесь: https://kassa.yandex.ru/developers/payments/payment-process#lifecycle
