### ISSUE TITLE
Proceed payment with an invalid card number

### ISSUE THREAD

**Issue by givotnoe** [yandex-money/yandex-checkout-android-sdk#5]
Hello, when I try to pay via a new card I can set focus on CVC EditText and get "done" ime action without filling in a card number (or filling this field with an invalid number) or any other fields. When I touch action button, app crashes with:

`IllegalStateException: proceedPay should be called only when all fields is correct`

SDK is used in test mode. Is it a bug or am I doing something wrong?

**Comment by drukarev** [comment]
Fixed in 1.3.0.3
