### ISSUE TITLE
Прямая оплата Google Pay

### ISSUE THREAD

**Issue by TooLazyy** [yandex-money/yandex-checkout-android-sdk#52]
Привет. Есть ли возможность сделать прямую оплату через google pay?
В приложении имеется собственный интерфейс для выбора способа оплаты, если юзер выберет оплату через google pay, то показывать ему еще один диалог с выбором будет не ок. В сдк такой функции что то не нашел.

**Comment by Winner28** [comment]
Здравствуйте! Извините за задержку.
Попробуйте следующее, в `PaymentParameters.PaymentParameters` укажите единственный метод оплаты - `PaymentMethodType.GOOGLE_PAY`.
Example: 
```
 val paymentParameters = PaymentParameters(
            Amount(BigDecimal.ONE, Currency.getInstance("RUB")),
            "Название товара",
            "Описание товара",
            "live_ID",
            "shop_id",
            SavePaymentMethod.OFF,
            setOf(PaymentMethodType.GOOGLE_PAY)
        )
```
