### ISSUE TITLE
Платежный токен не подходит

### ISSUE THREAD

**Issue by night-coal** [yandex-money/yandex-checkout-android-sdk#8]
Здравствуйте. Разъясните пожалуйста одну вещь

В этом колбэке
```
Checkout.setResultCallback((paymentToken, type) -> {
            getPresenter().onTokenizeResult(paymentToken, type.name());
            Log.e("PAY_TOKEN", paymentToken);
        });
```

Нам приходит вот такой токен:

```NewCard(id=3, charge=Amount(value=99.0, currency=RUB), fee=Fee(service=Amount(value=1, currency=RUB), counterparty=Amount(value=0.5, currency=RUB))), NewCardInfo(number='1111111111111026', expirationMonth='10', expirationYear='2020', csc='***'), Allow recurring payments: false```

При чем везде в документации токен платежа выглядит как хэш какой то строки:

`eyJ0eXBlIjoiY2hlY2tvdXRfanNfYmFua19jYXJkIiwiZW5jcnlwdGVkIjoiMFk3Q3dVVXFVSUE0bXVUWW5EVXhBRG9PUFFCRHByQ3F6Y0cvcGw5SDFZV0xKejROaS9wVkZ0amhmT3N1b1NzVGp2cFJzYkRxSTdLWStYNjZjdW45STczTC8zQXFPOGVwV0dtSFEyV1pXR1lHM3pNdUxyNHp1WmJzMW85bDh5czdjT0ZuMEc5T3hma0kyNitQcXBuSGU3NGZwYzRXU1l2TUh4MFpyYVdRNW5UdFlDVWQyZz09IiwiaW5pdFZlY3RvciI6Ik50d0lpZVFFaG9Cb3FJRzFxT29yREE9PSIsImtleUlkIjoiT2pOQUJrL21Uam5kTGtWZlR1U1F0dz09In0`

Подскажите пожалуйста, что нам делать с результатом из callback'a ?
Наш backend получает ошибку о неправильном токене, когда пытаемся провести платеж
И то, что приходит в колбэке, совсем не похоже на токен

Расчитываем на вашу помощь

**Comment by drukarev** [comment]
Добрый день.
Вам приходит тестовый токен. Вероятно, вы вызываете метод Checkout.configureTestMode() в своём коде. В этом методе первый параметр - использование моковых данных. Достаточно переключить флаг на false либо не вызывать этот метод, и начнёт приходит боевой токен.

В будущих версиях поменяем текст тестовых токенов, чтобы это было очевиднее.
