### ISSUE TITLE
Не отображается тестовая форма для подтверждения платежа

### ISSUE THREAD

**Issue by DarthMech** [yandex-money/yandex-checkout-android-sdk#9]
Для оплаты используется тестовый магазин, тестовый токен для SDK и тестовая карта с включенным 3dSecure. От api приходит ссылка на тестовую форму подтверждения оплаты.
Ссылка вида:
https://money.yandex.ru/api-pages/v3/3ds?acsUri=https%3A%2F%2Fdemo-scrat.yamoney.ru%3A8443%2Fmerchant-test-card-stub%2F3ds%3Ftes11%3D1%26amp%3Btest2%3D2&MD=1536663442128-3079210364026365123&PaReq=Q1VSUkVOQ1k9UlVSJlRFUk1JTkFMPTk5OTk5OCZFWFBfWUVBUj0yNSZQX1NJR049M2E3MmM2MGNhMjIyNjU4MTJhOTgwNmUzMjFmMTQyZTQ1NzVjMmQ0OCZSRVNQT05TRV9SUk49MjEwMzYzOTA5MzExJkVNQUlMPW5vcmVwbHklNDBtb25leS55YW5kZXgucnUmTUVSQ0hfTkFNRT1ZTSZERVNDPTIzMjliMzUxLTAwMGYtNTAwMC1hMDAwLTFlYTA0NWQzZjc5MSZSRVNQT05TRV9BVVRIQ09ERT05MDUwNTMmTUVSQ0hBTlQ9NzkwMzY3Njg2MjE5OTk5JkNBUkQ9MTExMTExMTExMTExMTAyNiZOQU1FPSZPUkRFUj01MDk2MzU0MTYyJk1FUkNIX1VSTD1tb25leS55YW5kZXgucnUmQU1PVU5UPTEuMDAmQkFDS1JFRj1odHRwcyUzQSUyRiUyRnNob3AuaWVnb3Jvdi5kb2Nkb2MucHJvJTJGbW9iaWxlJTJGcGF5bWVudC1maW5pc2hlZCZUSU1FU1RBTVA9MjAxODA5MTExMDU3MjImVFJUWVBFPTAmRVhQPTEyJkNWQzI9MTIzJk5PTkNFPTEyMzQ1Njc4OTBBQkNERUZlMjNhZGNlNTg4OGE4&TermUrl=https%3A%2F%2Fpaymentcard.yamoney.ru%3A443%2Fgates%2Fmb3dsdemoprovider

Ссылка открывается в браузере, например хром (отображается форма для подтверждения платежа), но при вызове метода sdk с данной ссылкой:
Intent intent = Checkout.create3dsIntent(context, url, redirectUrl)
startActivityForResult(intent, 1);
получаю пустой экран.

![screenshot_20180911-135740_docdoc](https://user-images.githubusercontent.com/11042504/45356317-9fdf4c00-b5cb-11e8-8837-70f24257e2f2.jpg)

**Comment by lynnfield** [comment]
Привет. Да, нам известна эта проблема. По какой-то причине WebView некорректно загружает url тестового 3ds. Для боевых 3ds все будет работать.

**Comment by gizmo-mogwai** [comment]
Прошу прощения за небольшой офф-топик, но у меня также вопрос по 3ds (на "боевых" данных). 
Пытаюсь заюзать приведенный в примере метод Checkout.create3dsIntent(context, url, redirectUrl), где:
- в качестве url указываю присланную яндексом ссылку на форму подтверждения
- в качестве redirectUrl забиваю существующий адрес-заглушку. 
После того, как юзер ввел корректный код из смс, происходит редирект по адресу-заглушке, и форма подтверждения не закрывается, остается висеть. Если закрыть ее вручную, то в вызывающую activitу вернется код результата RESULT_CANCELED.

Будучи новичком в вопросах реализации оплат, вполне допускаю, что просто не до конца разобралась в вопросе. Но в моем понимании, форма подтверждения все же должна закрываться самостоятельно после удачного введения кода. Подскажите, пожалуйста, какое поведение считается корректным и на что следует обратить внимание.

**Comment by lynnfield** [comment]
Поправили в версии 1.3.0.6
